#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2Y_2324_MidtermProject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Midterm")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPet(Pet instance);
    partial void UpdatePet(Pet instance);
    partial void DeletePet(Pet instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::_2Y_2324_MidtermProject.Properties.Settings.Default.MidtermConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Pet> Pets
		{
			get
			{
				return this.GetTable<Pet>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pets")]
	public partial class Pet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Pet_ID;
		
		private string _Avail_ID;
		
		private string _Pet_Type;
		
		private string _Pet_Breed;
		
		private int _Pet_Age;
		
		private string _Pet_DOB;
		
		private string _Pet_Gender;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPet_IDChanging(string value);
    partial void OnPet_IDChanged();
    partial void OnAvail_IDChanging(string value);
    partial void OnAvail_IDChanged();
    partial void OnPet_TypeChanging(string value);
    partial void OnPet_TypeChanged();
    partial void OnPet_BreedChanging(string value);
    partial void OnPet_BreedChanged();
    partial void OnPet_AgeChanging(int value);
    partial void OnPet_AgeChanged();
    partial void OnPet_DOBChanging(string value);
    partial void OnPet_DOBChanged();
    partial void OnPet_GenderChanging(string value);
    partial void OnPet_GenderChanged();
    #endregion
		
		public Pet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_ID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Pet_ID
		{
			get
			{
				return this._Pet_ID;
			}
			set
			{
				if ((this._Pet_ID != value))
				{
					this.OnPet_IDChanging(value);
					this.SendPropertyChanging();
					this._Pet_ID = value;
					this.SendPropertyChanged("Pet_ID");
					this.OnPet_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avail_ID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Avail_ID
		{
			get
			{
				return this._Avail_ID;
			}
			set
			{
				if ((this._Avail_ID != value))
				{
					this.OnAvail_IDChanging(value);
					this.SendPropertyChanging();
					this._Avail_ID = value;
					this.SendPropertyChanged("Avail_ID");
					this.OnAvail_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pet_Type
		{
			get
			{
				return this._Pet_Type;
			}
			set
			{
				if ((this._Pet_Type != value))
				{
					this.OnPet_TypeChanging(value);
					this.SendPropertyChanging();
					this._Pet_Type = value;
					this.SendPropertyChanged("Pet_Type");
					this.OnPet_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Breed", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pet_Breed
		{
			get
			{
				return this._Pet_Breed;
			}
			set
			{
				if ((this._Pet_Breed != value))
				{
					this.OnPet_BreedChanging(value);
					this.SendPropertyChanging();
					this._Pet_Breed = value;
					this.SendPropertyChanged("Pet_Breed");
					this.OnPet_BreedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Age", DbType="Int NOT NULL")]
		public int Pet_Age
		{
			get
			{
				return this._Pet_Age;
			}
			set
			{
				if ((this._Pet_Age != value))
				{
					this.OnPet_AgeChanging(value);
					this.SendPropertyChanging();
					this._Pet_Age = value;
					this.SendPropertyChanged("Pet_Age");
					this.OnPet_AgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_DOB", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pet_DOB
		{
			get
			{
				return this._Pet_DOB;
			}
			set
			{
				if ((this._Pet_DOB != value))
				{
					this.OnPet_DOBChanging(value);
					this.SendPropertyChanging();
					this._Pet_DOB = value;
					this.SendPropertyChanged("Pet_DOB");
					this.OnPet_DOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Pet_Gender
		{
			get
			{
				return this._Pet_Gender;
			}
			set
			{
				if ((this._Pet_Gender != value))
				{
					this.OnPet_GenderChanging(value);
					this.SendPropertyChanging();
					this._Pet_Gender = value;
					this.SendPropertyChanged("Pet_Gender");
					this.OnPet_GenderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
