<?xml version="1.0" encoding="utf-8"?><Database Name="Midterm" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=EVANLAPTOP\SQLEXPRESS;Initial Catalog=Midterm;Integrated Security=True;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="_2Y_2324_MidtermProject.Properties.Settings" SettingsPropertyName="MidtermConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pets" Member="Pets">
    <Type Name="Pet">
      <Column Name="Pet_ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Avail_ID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Breed" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_DOB" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>